src/main/webapp/WEB-INF/SQL/donghoon.sql, src/main/webapp/WEB-INF/views/mycontent/mail/mail.jsp
=> fix : mail.jsp 수정

src/main/webapp/WEB-INF/views/mycontent/calendar/calendar.jsp
commit이 되는지 확인하기 위해
태그를 추가했습니다!
=> fix :  calendar.jsp 수정

src/main/webapp/WEB-INF/views/mycontent/board/board.jsp
=> fix : board.jsp 수정

src/main/java/com/spring/app/employee/domain/AddressBookVO.java, src/main/java/com/spring/app/employee/domain/DepartmentVO.java, src/main/java/com/spring/app/employee/domain/EmployeeVO.java, src/main/java/com/spring/app/employee/domain/GroupVO.java, src/main/java/com/spring/app/employee/domain/PositionVO.java, src/main/java/com/spring/app/employee/domain/TeamVO.java, src/main/webapp/WEB-INF/SQL/jihye.sql
EmployeeVO, AddressBookVO, DepartmentVO, GroupVO, PositionVO,TeamVO 생성
=> feat : VO생성

src/main/webapp/WEB-INF/views/mycontent/board/board.jsp
=> fix : board.jsp

src/main/java/com/spring/app/employee/domain/AddressBookVO.java, src/main/java/com/spring/app/employee/domain/EmployeeVO.java
EmployeeVO  생일, 프로필 사진 추가
addressBookVO : 프로필 사진 추가
=> feat : VO 컬럼 추가

src/main/resources/static/css/header.css, src/main/resources/static/js/header.js, src/main/resources/static/smarteditor/js/SE2BasicCreator.js, src/main/webapp/WEB-INF/views/header/header.jsp, src/main/webapp/WEB-INF/views/mycontent/calendar/calendar.jsp
=> fix : header.jsp 수정

src/main/resources/static/css/email/email_main.css, src/main/resources/static/css/header.css, src/main/resources/static/css/main-section.css, src/main/resources/static/js/email/email.js, src/main/webapp/WEB-INF/views/header/header.jsp, src/main/webapp/WEB-INF/views/mycontent/calendar/calendar.jsp
이제 각자 calendar.jsp 페이지에서 참고해서 기능구현 하시면 됩니다!
=> fix : calendar.jsp 예시 페이지 작성

src/main/java/com/spring/app/commute/controller/CommuteController.java, src/main/java/com/spring/app/employee/domain/EmployeeVO.java
=> fix : 자잘한 오류 수정

.gitignore, src/main/resources/static/css/document/document_main.css, src/main/resources/static/js/document/document.js, src/main/webapp/WEB-INF/SQL/sunghoon.sql, src/main/webapp/WEB-INF/views/mycontent/document/document.jsp
document_main.css, document.js : 전자결제 페이지 css, js 생성
document.jsp : 전자결재 view 수정
.gitignore 수정
=> fix : document.jsp 전자결재 veiw 단 수정

src/main/java/com/spring/app/commute/controller/CommuteController.java, src/main/java/com/spring/app/employee/controller/EmployeeController.java, src/main/java/com/spring/app/employee/domain/AddressBookVO.java, src/main/java/com/spring/app/employee/domain/BookMarkVO.java, src/main/java/com/spring/app/employee/domain/EmployeeVO.java, src/main/java/com/spring/app/employee/domain/GroupVO.java, src/main/java/com/spring/app/employee/domain/PositionVO.java, src/main/java/com/spring/app/employee/domain/TeamVO.java, src/main/java/com/spring/app/employee/service/EmployeeService.java, src/main/java/com/spring/app/employee/service/EmployeeService_imple.java, src/main/resources/mybatis/mapper/employee.xml, src/main/webapp/WEB-INF/SQL/jihye.sql, src/main/webapp/WEB-INF/views/mycontent/employee/admin_main.jsp, src/main/webapp/WEB-INF/views/mycontent/employee/login.jsp
=> feat: 로그인 기능 완성

src/main/java/com/spring/app/employee/controller/EmployeeController.java, src/main/java/com/spring/app/employee/model/EmployeeDAO.java, src/main/java/com/spring/app/employee/service/EmployeeService.java, src/main/java/com/spring/app/employee/service/EmployeeService_imple.java, src/main/resources/mybatis/mapper/employee.xml, src/main/resources/static/css/employeeCss/addEmployee.css, src/main/resources/static/css/employeeCss/adminMain.css, src/main/webapp/WEB-INF/SQL/jihye.sql, src/main/webapp/WEB-INF/views/mycontent/employee/MyPage.jsp, src/main/webapp/WEB-INF/views/mycontent/employee/addEmployee.jsp, src/main/webapp/WEB-INF/views/mycontent/employee/admin_main.jsp, src/main/webapp/WEB-INF/views/mycontent/employee/login.jsp
=> feat: 회원추가(정규식표현x)

src/main/java/com/spring/app/document/controller/DocumentController.java, src/main/java/com/spring/app/document/domain/DocumentVO.java, src/main/java/com/spring/app/document/model/DocumentDAO.java, src/main/java/com/spring/app/document/service/DocumentService.java, src/main/java/com/spring/app/document/service/DocumentService_imple.java, src/main/resources/mybatis/mapper/document.xml, src/main/webapp/WEB-INF/SQL/sunghoon.sql, src/main/webapp/WEB-INF/views/mycontent/document/deptDocumentList.jsp, src/main/webapp/WEB-INF/views/mycontent/document/document_main.jsp, src/main/webapp/WEB-INF/views/mycontent/document/myDocumentList.jsp, src/main/webapp/WEB-INF/views/mycontent/document/tempList.jsp
=> feat : 부서문서함 페이지 생성

src/main/java/com/spring/app/MyspringApplication.java, src/main/java/com/spring/app/common/FileManager.java, src/main/java/com/spring/app/common/GoogleMail.java, src/main/java/com/spring/app/common/MySMTPAuthenticator.java, src/main/java/com/spring/app/document/controller/DocumentController.java, src/main/resources/mybatis/mapper/document.xml, src/main/webapp/WEB-INF/views/mycontent/document/annual.jsp, src/main/webapp/WEB-INF/views/mycontent/document/deptDocumentList.jsp, src/main/webapp/WEB-INF/views/mycontent/document/myDocumentList.jsp, src/main/webapp/WEB-INF/views/mycontent/document/tempList.jsp
결재 라인 추가 기능, GoogleMail 기능 추가, 스케줄러 사용 가능하게 수정
=> feat : 결재 라인 추가 기능

src/main/java/com/spring/app/employee/controller/EmployeeController.java, src/main/java/com/spring/app/employee/domain/EmployeeVO.java, src/main/java/com/spring/app/employee/model/EmployeeDAO.java, src/main/java/com/spring/app/employee/service/EmployeeService.java, src/main/java/com/spring/app/employee/service/EmployeeService_imple.java, src/main/resources/mybatis/mapper/employee.xml, src/main/resources/static/css/employeeCss/myPage.css, src/main/webapp/WEB-INF/SQL/jihye.sql, src/main/webapp/WEB-INF/views/mycontent/employee/MyPage.jsp, src/main/webapp/WEB-INF/views/mycontent/employee/addEmployee.jsp, src/main/webapp/WEB-INF/views/mycontent/employee/adminLeftBar.jsp, src/main/webapp/WEB-INF/views/mycontent/employee/admin_main.jsp, src/main/webapp/WEB-INF/views/mycontent/employee/login.jsp, src/main/webapp/WEB-INF/views/mycontent/employee/myPage.jsp, src/main/webapp/WEB-INF/views/mycontent/employee/myPageLeftBar.jsp, src/main/webapp/WEB-INF/views/mycontent/employee/updateMypageInfo.jsp, src/main/webapp/WEB-INF/views/mycontent/employee/updateMypageInfoLeftBar.jsp, src/main/webapp/WEB-INF/views/mycontent/employee/정규표현식정리.txt
사원 추가 : 사번, 비밀번호, 이름, 이메일 유효성 검사 추가함
=> perf :사원 추가 유효성 검사 추가

src/main/java/com/spring/app/mail/controller/MailController.java, src/main/java/com/spring/app/mail/domain/MailVO.java, src/main/java/com/spring/app/mail/model/MailDAO.java, src/main/java/com/spring/app/mail/service/MailService.java, src/main/java/com/spring/app/mail/service/MailService_imple.java, src/main/resources/mybatis/mapper/mail.xml, src/main/resources/static/css/email/email_main.css, src/main/resources/static/js/email/email.js, src/main/webapp/WEB-INF/SQL/donghoon.sql, src/main/webapp/WEB-INF/views/mycontent/mail/mail.jsp, src/main/webapp/WEB-INF/views/mycontent/mail/mailPage.jsp
총 메일 수, 안읽은 메일 수 표시
새로고침 버튼 적용
임시보관함, 중요메일함 활성화
=> fix : 메일 중요표시, 읽음표시, 체크박스 기능 추가

src/main/java/com/spring/app/employee/controller/EmployeeController.java, src/main/java/com/spring/app/employee/domain/AddressBookVO.java, src/main/java/com/spring/app/employee/model/EmployeeDAO.java, src/main/java/com/spring/app/employee/service/EmployeeService.java, src/main/java/com/spring/app/employee/service/EmployeeService_imple.java, src/main/resources/mybatis/mapper/employee.xml, src/main/resources/mybatis/mybatis-config.xml, src/main/resources/static/css/employeeCss/addressbook.css, src/main/resources/static/css/employeeCss/adminMain.css, src/main/resources/static/css/employeeCss/updateEmployee_by_addmin.css, src/main/webapp/WEB-INF/views/mycontent/employee/addEmployee.jsp, src/main/webapp/WEB-INF/views/mycontent/employee/addressbook.jsp, src/main/webapp/WEB-INF/views/mycontent/employee/addressbookbar.jsp, src/main/webapp/WEB-INF/views/mycontent/employee/admin_main.jsp, src/main/webapp/WEB-INF/views/mycontent/employee/department_addressbook.jsp, src/main/webapp/WEB-INF/views/mycontent/employee/external_addressbook.jsp, src/main/webapp/WEB-INF/views/mycontent/employee/login.jsp, src/main/webapp/WEB-INF/views/mycontent/employee/updateEmployee.jsp, src/main/webapp/WEB-INF/views/mycontent/employee/updateMypageInfo.jsp
로그인 : 포커스 뺌 , 경고문에 ! 뺌, 로그인 마우스 클릭 만듦
사원 추가 : date 키보드 입력 막음
사원 정보 수정 : date 키보드 입력 막음, 유효성 검사o
관리자의 사원정보 수정 뷰단 만듦
addressbook VO : 오타 수정 > directCall, fk_employeeNo 수정 주소록 등록(유효성 검사o)
전체 주소록, 부서주소록, 외부주소록 만듦
=> feat: 주소록 추가

src/main/java/com/spring/app/employee/controller/EmployeeController.java, src/main/java/com/spring/app/employee/model/EmployeeDAO.java, src/main/java/com/spring/app/employee/service/EmployeeService.java, src/main/java/com/spring/app/employee/service/EmployeeService_imple.java, src/main/resources/mybatis/mapper/employee.xml, src/main/resources/static/css/employeeCss/addressbook.css, src/main/resources/static/css/header.css, src/main/webapp/WEB-INF/SQL/jihye.sql, src/main/webapp/WEB-INF/views/header/header.jsp, src/main/webapp/WEB-INF/views/mycontent/employee/addressbook.jsp, src/main/webapp/WEB-INF/views/mycontent/employee/department_addressbook.jsp, src/main/webapp/WEB-INF/views/mycontent/employee/detail_addressbook.jsp, src/main/webapp/WEB-INF/views/mycontent/employee/external_addressbook.jsp, src/main/webapp/WEB-INF/views/mycontent/employee/myPage.jsp, src/main/webapp/WEB-INF/views/mycontent/employee/updateEmployee.jsp
헤더 : 마이페이지 링크 추가, 주소록 링크 추가
주소록 : 주소록 삭제 완료
=> feat: 주소록 삭제

src/main/java/com/spring/app/board/controller/BoardController.java, src/main/java/com/spring/app/config/Interceptor_Configuration.java, src/main/resources/static/css/board/board_main2.css, src/main/resources/static/js/board/board2.js, src/main/webapp/WEB-INF/views/mycontent/board/board2.jsp, src/main/webapp/WEB-INF/views/mycontent/board/boardLeftBar.jsp
=> feat : Interceptor_Configuration 경로, FlowUp 메인페이지용 게시판 조각

src/main/java/com/spring/app/document/controller/DocumentController.java, src/main/java/com/spring/app/document/domain/DocumentVO.java, src/main/java/com/spring/app/document/model/DocumentDAO.java, src/main/java/com/spring/app/document/service/DocumentService.java, src/main/java/com/spring/app/document/service/DocumentService_imple.java, src/main/resources/mybatis/mapper/document.xml, src/main/resources/static/css/document/document.css, src/main/resources/static/css/document/document_main.css, src/main/resources/static/js/document/document.js, src/main/webapp/WEB-INF/SQL/sunghoon.sql, src/main/webapp/WEB-INF/views/mycontent/document/approvedList.jsp, src/main/webapp/WEB-INF/views/mycontent/document/deptDocumentList.jsp, src/main/webapp/WEB-INF/views/mycontent/document/document.jsp, src/main/webapp/WEB-INF/views/mycontent/document/documentView.jsp, src/main/webapp/WEB-INF/views/mycontent/document/document_box.jsp, src/main/webapp/WEB-INF/views/mycontent/document/document_main.jsp, src/main/webapp/WEB-INF/views/mycontent/document/draftForm.jsp, src/main/webapp/WEB-INF/views/mycontent/document/myDocumentList.jsp, src/main/webapp/WEB-INF/views/mycontent/document/tempList.jsp, src/main/webapp/WEB-INF/views/mycontent/document/todoList.jsp, src/main/webapp/WEB-INF/views/mycontent/document/upcomingList.jsp
전자결재 메인페이지
결재 긴급 기능 추가
문서함 결재상태/결재양식 으로 검색 기능 추가
=> feat : 전자결재 메인페이지

src/main/java/com/spring/app/mail/controller/MailController.java, src/main/java/com/spring/app/mail/domain/MailFileVO.java, src/main/java/com/spring/app/mail/domain/MailVO.java, src/main/java/com/spring/app/mail/domain/ReferencedVO.java, src/main/java/com/spring/app/mail/model/MailDAO.java, src/main/java/com/spring/app/mail/model/MailDAO_imple.java, src/main/java/com/spring/app/mail/service/MailService.java, src/main/java/com/spring/app/mail/service/MailService_imple.java, src/main/resources/mybatis/mapper/mail.xml, src/main/resources/static/js/email/email.js, src/main/webapp/WEB-INF/SQL/donghoon.sql, src/main/webapp/WEB-INF/views/mycontent/mail/mail.jsp
체크박스 Bad Request,
메일 작성 에러,
메일 중복 작성,
메일 작성 파일첨부
=> fix : 메일 다수 기능 수정

src/main/java/com/spring/app/employee/controller/EmployeeController.java, src/main/java/com/spring/app/employee/model/EmployeeDAO.java, src/main/java/com/spring/app/employee/service/EmployeeService.java, src/main/java/com/spring/app/employee/service/EmployeeService_imple.java, src/main/resources/mybatis/mapper/employee.xml, src/main/resources/mybatis/mybatis-config.xml, src/main/resources/static/css/employeeCss/addressbook.css, src/main/webapp/WEB-INF/SQL/jihye.sql, src/main/webapp/WEB-INF/views/mycontent/employee/addressbook.jsp, src/main/webapp/WEB-INF/views/mycontent/employee/addressbookbar.jsp, src/main/webapp/WEB-INF/views/mycontent/employee/login.jsp
=> feat: 주소록에 그룹옵션추가

src/main/webapp/WEB-INF/SQL/jihye.sql, src/main/webapp/WEB-INF/views/mycontent/employee/addEmployee.jsp, src/main/webapp/WEB-INF/views/mycontent/employee/addressbook.jsp, src/main/webapp/WEB-INF/views/mycontent/employee/addressbookbar.jsp, src/main/webapp/WEB-INF/views/mycontent/employee/myPageLeftBar.jsp, src/main/webapp/WEB-INF/views/mycontent/employee/updateEmployee.jsp
시큐리티 레벨 10 이상 아이디로 로그인시 leftbar에 관리자 기능 생김
=> chore : 마이페이지 관리자 기능 넣음
